databases:
  - name: taskflow-db
    plan: free
    databaseName: taskflow
    user: taskflow

services:
  - type: redis
    name: taskflow-redis
    plan: free
    ipAllowList: [] # keeps it internal only

  - type: web
    name: taskflow-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run db:generate && npm run build
    startCommand: npm run db:deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: taskflow-redis
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

  - type: worker
    name: taskflow-worker
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run db:generate && npm run build
    startCommand: npm run start:worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: taskflow-redis
          property: connectionString
      - key: JWT_ACCESS_SECRET
        fromService:
          type: web
          name: taskflow-api
          envVarKey: JWT_ACCESS_SECRET
      - key: JWT_REFRESH_SECRET
        fromService:
          type: web
          name: taskflow-api
          envVarKey: JWT_REFRESH_SECRET
